image: docker:latest
services:
  - docker:dind

stages:
  - build
#  - package
#  - deploy

server-build:
  image: gradle:4.4.1-jdk8-alpine
  stage: build
  script:
    - cd server
    - "./gradlew build"