image: docker:latest

services:
  - docker:dind

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - client/node_modules

stages:
  - build
  - test
#  - deploy

server-build:
  image: gradle:4.4.1-jdk8-alpine
  stage: build
  script:
    - "cd server"
    - "./gradlew build"
    - "cd .."
  artifacts:
    paths:
      - server/build/reports/*
      - server/build/libs/*

server-test:
  image: gradle:4.4.1-jdk8-alpine
  stage: test
  script:
    - "cd server"
    - "./gradlew check test jacocoTestReport --no-daemon"
    - "cd .."
  artifacts:
    paths:
      - server/build/reports/*

client-build:
  image: monostream/nodejs-angular-cli:latest
  stage: build
  script:
    - cd client
    - "yarn install"
    - "ng build"
    - "cd .."

client-test:
  image: teracy/angular-cli:latest
  stage: test
  script:
    - cd client
    - "yarn install"
    - "ng lint test --browsers Chrome_no_sandbox --single-run=true --watch=false"
    - "cd .."
